services:
  reservation-mysql:
    image: mysql:8.4
    container_name: reservation-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: reservation_db
      MYSQL_USER: reservation_user
      MYSQL_PASSWORD: reservation_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"

    volumes:
      - reservation_mysql_data:/var/lib/mysql

  reservation-redis:
    image: redis:7.4-alpine
    container_name: reservation-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

volumes:
  reservation_mysql_data: