spring:
  application:
    name: reservation-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/reservation_db}
    username: ${DB_USERNAME:reservation_user}
    password: ${DB_PASSWORD:reservation_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 1s
      timeout: 1s

app:
  slots-cache:
    enabled: ${SLOTS_CACHE_ENABLED:true}

server:
  port: 8080

security:
  jwt:
    secret: "PtKhd0onRsnE8SgZUO4Jp2eBWYd3DTg9llEQ5DcyM+M="
    access-token-expiration: 1h
